src/PlaneswalkersPantry/Models/Card.cs
using System.ComponentModel.DataAnnotations;

using MySqlConnector;

namespace PlaneswalkersPantry.Models;

public class Card
{
    public static Card? Find(int cardNumber)
    {
        MySqlConnection conn = Database.CreateConnection();
        using (MySqlCommand command = new MySqlCommand("SELECT * FROM CARD WHERE (CARD_NUMBER = @num)", conn))
        {
            command.Parameters.Add(new MySqlParameter("num", cardNumber));
            using var results = command.ExecuteReader();
            results.Read();

            if (!results.HasRows)
            {
                results.Close();
                conn.Close();
                return null;
            }

            Card card = Card.FromSqlRow(results);

            results.NextResult();
            bool hasMoreRows = results.Read();
            results.Close();
            conn.Close();

            if (hasMoreRows)
                throw new InvalidOperationException($"More than one card with CARD_NUMBER {cardNumber}");

            return card;
        }
    }

    public static Card FromSqlRow(MySqlDataReader results)
    {
        static string? FixDbNull(MySqlDataReader reader, string columnName)
        {
            try
            {
                return reader.GetString(columnName);
            }
            catch (InvalidCastException)
            {
                // This happens if DBNull is found.
                return null;
            }
        }

        Card card = new Card();
        card.CardNumber = results.GetInt32("CARD_NUMBER");
        card.Title = results.GetString("CARD_TITLE");
        card.ManaCost = results.GetString("MANA_COST");
        card.RulesText = results.GetString("RULES_TEXT");
        card.FlavorText = FixDbNull(results, "FLAVOR_TEXT");
        card.SetCode = results.GetString("SET_CODE");
        card.Rarity = results.GetString("RARITY_CODE") switch
        {
            "C" => CardRarity.Common,
            "U" => CardRarity.Uncommon,
            "R" => CardRarity.Rare,
            "M" => CardRarity.MythicRare,
            _ => throw new ArgumentException($"Unrecognized RARITY_CODE for card {card.Title}")
        };
        card.Power = FixDbNull(results, "POWER");
        card.Toughness = FixDbNull(results, "TOUGHNESS");
        card.TypeLine = results.GetString("TYPE_LINE");
        card.NumberOwned = results.GetUInt32("NUMBER_OWNED");

        return card;
    }

    public int GetNumberCheckedOut()
    {
        int count;

        using MySqlConnection conn = Database.CreateConnection();
        using (MySqlCommand command =
               new MySqlCommand("SELECT SUM(COUNT) AS COUNT FROM CARD_IN_CHECKOUT " +
                                "JOIN CHECKOUT ON CHECKOUT.CHECKOUT_NUMBER = CARD_IN_CHECKOUT.CHECKOUT_NUMBER " +
                                "WHERE (CARD_NUMBER = @num AND CHECKOUT.STATUS = 1)", conn))
        {
            command.Parameters.Add(new MySqlParameter("num", CardNumber));
            MySqlDataReader results = command.ExecuteReader();

            results.Read();

            try
            {
                count = results.GetInt32("COUNT");
            }
            catch (InvalidCastException)
            {
                // This happens if DBNull is found.
                count = 0;
            }

            results.Close();
        }

        conn.Close();
        return count;
    }

    public int GetNumberAvailable() => (int)NumberOwned - GetNumberCheckedOut();

    [Required] public int CardNumber { get; set; }
    [Required] public string? Title { get; set; }
    public string? ManaCost { get; set; }
    public string? RulesText { get; set; }
    public string? FlavorText { get; set; }
    [Required] public string? SetCode { get; set; }
    public CardRarity Rarity { get; set; } = CardRarity.Common;
    public string? Power { get; set; }
    public string? Toughness { get; set; }
    public string? TypeLine { get; set; }
    [Required] public uint NumberOwned { get; set; }
}

public enum CardRarity
{
    Common,
    Uncommon,
    Rare,
    MythicRare
}

src/PlaneswalkersPantry/Controllers/CardController.cs
using System.Text;

using Microsoft.AspNetCore.Mvc;

using MySqlConnector;

using PlaneswalkersPantry.Models;
using PlaneswalkersPantry.Models.ViewModels;

namespace PlaneswalkersPantry.Controllers;

public class CardController : Controller
{
    private SessionAccess Session;

    public CardController(SessionAccess session)
    {
        Session = session;
    }

    public IActionResult AddToBasket(int cardNumber)
    {
        AddCardToBasketViewModel viewModel = new AddCardToBasketViewModel();

        Card? card = Card.Find(cardNumber);
        if (card == null) throw new InvalidOperationException($"Card with ID {cardNumber} not found");

        viewModel.Card = card;
        viewModel.Count = 1;
        viewModel.CardSet = CardSet.Find(card.SetCode!);

        return View(viewModel);
    }

    [HttpPost]
    public IActionResult AddToBasket(AddCardToBasketViewModel model)
    {
        string? userName = Session.AuthenticatedUserName;
        if (userName == null) throw new UnauthorizedAccessException("You need to be logged in to do this");

        Checkout? basket = Checkout.GetBasket(userName, true);
        if (basket == null) throw new InvalidOperationException("Basket was not created");
        basket.AddCard(model.Card!, (uint)model.Count);

        return LocalRedirect("/Checkout/Basket");
    }

    public IActionResult Search()
    {
        return View(new CardSearchViewModel());
    }

    [HttpPost]
    public IActionResult Search(CardSearchViewModel model)
    {
        using MySqlConnection conn = Database.CreateConnection();
        List<MySqlParameter> parameters = new List<MySqlParameter>();

        StringBuilder query = new StringBuilder();
        query.Append("SELECT * FROM CARD");

        if (!string.IsNullOrWhiteSpace(model.Name) || !string.IsNullOrEmpty(model.Content) || model.SetCode != "***")
        {
            bool needsJoinOp = false;
            string joinOp = model.Predicate switch
            {
                CardSearchViewModel.SearchPredicate.And => " AND ",
                CardSearchViewModel.SearchPredicate.Or => " OR ",
                _ => throw new ArgumentException("Unexpected search predicate")
            };

            query.Append(" WHERE (");

            if (!string.IsNullOrWhiteSpace(model.Name))
            {
                query.Append("CARD_TITLE LIKE @title");
                parameters.Add(new MySqlParameter("title", $"%{model.Name}%"));
                needsJoinOp = true;
            }

            if (!string.IsNullOrWhiteSpace(model.Content))
            {
                if (needsJoinOp) query.Append(joinOp);

                query.Append("RULES_TEXT LIKE @content");
                parameters.Add(new MySqlParameter("content", $"%{model.Content}%"));
                needsJoinOp = true;
            }

            if (model.SetCode != "***")
            {
                if (needsJoinOp) query.Append(joinOp);

                query.Append("SET_CODE = @set_code");
                parameters.Add(new MySqlParameter("set_code", model.SetCode));
            }

            query.Append(");");
        }

        using (MySqlCommand command = new MySqlCommand(query.ToString(), conn))
        {
            command.Parameters.AddRange(parameters.ToArray());

            using var results = command.ExecuteReader();
            bool hasRows = results.Read();

            List<Card> cards = new List<Card>();
            while (hasRows)
            {
                cards.Add(Card.FromSqlRow(results));
                hasRows = results.Read();
            }

            model.Results = cards.Any() ? cards : Enumerable.Empty<Card>();
        }

        return View(model);
    }
}

src/PlaneswalkersPantry/Views/Card/AddToBasket.cshtml
@{
    ViewData["Title"] = "Add Card to Basket";
}

@model PlaneswalkersPantry.Models.ViewModels.AddCardToBasketViewModel

<main class="row">
    <h1>Add Card to Basket</h1>
    <div class="row card-details">
        <h4>@Model.Card!.Title (<i>@Model.CardSet!.SetName</i>)</h4>
        <p>
            @Model.Card.Rarity.ToDisplayString() &ndash; @Model.Card.NumberOwned.ToString("D") Owned
        </p>
        <p>
            <b>@Model.Card.TypeLine</b>
            @if (!string.IsNullOrEmpty(Model.Card.ManaCost))
            {
                <span>
                    &mdash; @Model.Card.ManaCost
                </span>
            }
        </p>
        <p>
            @Model.Card.RulesText
        </p>

        @if (!string.IsNullOrWhiteSpace(Model.Card.FlavorText))
        {
            <p>
                <i>@Model.Card.FlavorText</i>
            </p>
        }

        @if (!string.IsNullOrWhiteSpace(Model.Card.Power) && !string.IsNullOrEmpty(Model.Card.Toughness))
        {
            <p>
                @Model.Card.Power&nbsp;/&nbsp;@Model.Card.Toughness
            </p>
        }
    </div>

    <h3>How many cards do you wish to borrow?</h3>
    <form asp-controller="Card" asp-action="AddToBasket">
        <p>
            <input type="number" asp-for="Count" id="CountParameter" min="1" max=@Model.Card.GetNumberAvailable() class="form-control">
        </p>
        <p>
            <input type="hidden" name="CardNumber" value=@Model.CardNumber>
            <input type="submit" value="Add to Basket" class="btn">
        </p>
    </form>
</main>

src/PlaneswalkersPantry/Views/Card/Search.cshtml
@{
    ViewData["Title"] = "Search Cards";
}

@using System.Linq
@model PlaneswalkersPantry.Models.ViewModels.CardSearchViewModel
@inject SessionAccess Session

<main class="row">
    <h1>Search Cards</h1>

    <form asp-action="Search" asp-controller="Card" method="post" class="form-block" style="margin-bottom: 50px">
        <div class="form-block-content">
            <p>
                <select asp-for="Predicate" asp-items="Model.SearchPredicateOptions" class="form-select-lg"></select>
            </p>

            <p>
                <label asp-for="Name" class="align-right control-label">Card name:</label>
                <input asp-for="Name" class="form-control">
            </p>
            <p>
                <label asp-for="Content" class="align-right control-label">Text in card body:</label>
                <input asp-for="Content" class="form-control">
            </p>
            <p>
                <label asp-for="SetCode" class="align-right control-label">Card set:</label>
                <select asp-for="SetCode" asp-items="Model.SetNameOptions" class="form-select-lg"></select>
            </p>
        </div>

        <div class="form-block-footer">
            <button type="submit" class="btn btn-primary">Search</button>
        </div>
    </form>

    @if (Model.Results != null && Model.Results.Any())
    {
        <div>
            @foreach (Card card in Model.Results)
            {
                <div class="row card-details">
                    <h4>@card.Title (<i>@Model.CardSets[card.SetCode!].SetName</i>)</h4>
                    <p>
                        @card.Rarity.ToDisplayString() &ndash; @card.NumberOwned.ToString("D") Owned,
                        @card.GetNumberAvailable() Available
                    </p>
                    <p>
                        <b>@card.TypeLine</b>
                        @if (!string.IsNullOrEmpty(card.ManaCost))
                        {
                            <span>
                                &mdash; @card.ManaCost
                            </span>
                        }
                    </p>
                    <p>
                        @card.RulesText
                    </p>

                    @if (!string.IsNullOrWhiteSpace(card.FlavorText))
                    {
                        <p>
                            <i>@card.FlavorText</i>
                        </p>
                    }

                    @if (!string.IsNullOrWhiteSpace(card.Power) && !string.IsNullOrEmpty(card.Toughness))
                    {
                        <p>
                            @card.Power&nbsp;/&nbsp;@card.Toughness
                        </p>
                    }

                    @if (Session.IsSignedIn())
                    {
                        <p>
                            @if (card.GetNumberAvailable() > 0)
                            {
                                <a asp-controller="Card" asp-action="AddToBasket" asp-route-cardNumber=@card.CardNumber>
                                    Add to Basket
                                </a>
                            }
                            else
                            {
                                <b>No cards available</b>
                            }
                        </p>
                    }
                </div>
            }
        </div>
    }
    else if (Model.Results != null && !Model.Results.Any())
    {
        <h4>No results found.</h4>
    }
</main>